# Site settings
title: Amer's Data Day
header-img: img/home-bg.jpg
email: amer.shalan@gmail.com
copyright_name: Amer Shalan
description: "Amer Shalan, the data science man!"
baseurl: ""
url: "https://ashalan.github.io"
twitter_username: pterodactylitis
github_username:  ashalan
email_username:  amer.shalan@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-85178690-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag]